version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: agentic_rag_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-agentic_rag}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-agentic_rag}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - agentic_rag_network

volumes:
  postgres_data:
    driver: local

networks:
  agentic_rag_network:
    driver: bridge
